// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TempleScheduler.Models;

namespace TempleScheduler.Migrations
{
    [DbContext(typeof(AppointmentContext))]
    partial class AppointmentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("TempleScheduler.Models.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupSize")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("GroupId");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            GroupId = 1,
                            Email = "group4-1@gmail.com",
                            GroupName = "4-1",
                            GroupSize = "4",
                            Phone = "123-456-7890"
                        },
                        new
                        {
                            GroupId = 2,
                            Email = "group4-2@gmail.com",
                            GroupName = "4-2",
                            GroupSize = "5",
                            Phone = "111-222-3333"
                        },
                        new
                        {
                            GroupId = 3,
                            Email = "group4-3@gmail.com",
                            GroupName = "4-3",
                            GroupSize = "6",
                            Phone = "555-555-5555"
                        });
                });

            modelBuilder.Entity("TempleScheduler.Models.TimeSlot", b =>
                {
                    b.Property<int>("TimeSlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Time")
                        .HasColumnType("INTEGER");

                    b.HasKey("TimeSlotId");

                    b.HasIndex("GroupId");

                    b.ToTable("TimeSlots");
                });

            modelBuilder.Entity("TempleScheduler.Models.TimeSlot", b =>
                {
                    b.HasOne("TempleScheduler.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId");
                });
#pragma warning restore 612, 618
        }
    }
}
